flow/cclock/lock/urls.py
from django.conf.urls.defaults import *
import workflow.settings

urlpatterns = patterns('workflow.flow.cclock.lock',
    # Example:
    # (r'^unicenter/', include('unicenter.foo.urls')),

    # Uncomment this for admin:
    #(r'^$', 'views.index'),
    (r'^$', 'views.index'),
)

flow/cclock/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('workflow.flow.cclock',
    # Example:
    # (r'^unicenter/', include('unicenter.foo.urls')),

    # Uncomment this for admin:
    #(r'^$', 'views.index'),
    (r'^lock/', include('workflow.flow.cclock.lock.urls')),
    (r'^checkmr/', include('workflow.flow.cclock.checkmr.urls')),
    (r'^my/$', 'views.my_cclocks'),
    (r'^my/add/$', 'views.add'),
    (r'^my/newFlow2newMR/$', 'views.newFlow2newMR'),
    (r'^my/(?P<id>\d+)/$', 'views.view'),
    (r'^my/(?P<id>\d+)/rfb_mr/$', 'views.rfb_mr'),
    
    (r'^todo/?q_approve_result=o$', 'views.view_all_approved_result'),
    (r'^todo/$', 'views.todo_cclocks'),
    (r'^todo/(?P<id>\d+)/$', 'views.view'),
    (r'^todo/(?P<id>\d+)/approve/$', 'views.approve'),
    (r'^todo/(?P<id>\d+)/cclock_update/$','views.update'),
    (r'^todo/query','views.query'),
)

urls.py
from django.conf.urls.defaults import *
from workflow import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
try:
    admin.autodiscover()
except:
    pass

urlpatterns = patterns('',
    # Example:
    # (r'^cclock/', include('cclock.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve',
    #    {'document_root': settings.MEDIA_ROOT}),    
    (r'^admin/(.*)', admin.site.root),
    (r'^mr_flow/',include('workflow.mr_flow.urls')),
    (r'^cclock/', include('workflow.flow.cclock.urls')),
    (r'^mr_review/', include('workflow.MrReview.urls')),
    (r'^spec/', include('workflow.Spec.urls')),
    (r'^', include('workflow.portal.urls')),
    (r'^newfile/', include('workflow.addnewfile.urls')),
    (r'^vob_config/',include('workflow.VobConfig.urls')),
)

workflow/urls.py
from django.conf.urls.defaults import *
from workflow import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
try:
    admin.autodiscover()
except:
    pass

urlpatterns = patterns('',
    # Example:
    # (r'^cclock/', include('cclock.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
    (r'^admin/(.*)', admin.site.root),
    (r'^mr_flow/',include('workflow.mr_flow.urls')),
    (r'^cclock/', include('workflow.flow.cclock.urls')),
    (r'^mr_review/', include('workflow.MrReview.urls')),
    (r'^spec/', include('workflow.Spec.urls')),
    (r'^', include('workflow.portal.urls')),
    (r'^newfile/', include('workflow.addnewfile.urls')),
    (r'^vob_config/',include('workflow.VobConfig.urls')),
    (r'^release_tool/',include('workflow.ReleaseTool.urls')),
    (r'^product_manage/',include('workflow.Product.urls')),
)

flow/cclock/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from workflow.VobConfig.views import get_branch_choices

class MR(models.Model):
    mr_id=models.CharField(primary_key=True, max_length=100)#MR ID
    mr_headline=models.CharField(max_length=255, blank=True, null=True)#MR标题
    mr_state=models.CharField(max_length=50, blank=True, null=True)#MR标题

class CCLockFlow(models.Model):
    """
    提交的MR
    审批人直接在数据库里进行配置，不需要保存在数据库
    数据库中只记录最后执行了审批操作的审批人
    primary_approver#主审核人
    sec_approver#第二审核人
    """
    #TODO 必须要有MR查询功能，不然无法
    #提交后就无法修改撤销
    title=models.CharField(max_length=100)#标题
    descn=models.TextField(blank=True)#描述
    bugs = models.ManyToManyField(MR, blank=True, null=True, \
            verbose_name="list of bugs")#bug列表
    vob_branch_1 = models.CharField(max_length=100, choices=get_branch_choices())#分支
    vob_branch_2 = models.CharField(blank=True, null=True, max_length=100, choices=get_branch_choices())#分支
    vob_branch_3 = models.CharField(blank=True, null=True, max_length=100, choices=get_branch_choices())#分支
    vob_branch_4 = models.CharField(blank=True, null=True, max_length=100, choices=get_branch_choices())#分支
    vob_branch_5 = models.CharField(blank=True, null=True, max_length=100, choices=get_branch_choices())#分支
    vob_branch_6 = models.CharField(blank=True, null=True, max_length=100, choices=get_branch_choices())#分支
    who_approver = models.ForeignKey(User, verbose_name="who_approver", blank=True, null=True, \
            related_name="toapp_cclocks")#审批人
    approve_result = models.CharField(max_length=1, blank=True, null=True, \
            choices=(('', u'待审批'), ('o', u'通过'), ('x', u'驳回')))#审核结果
    approve_note = models.TextField(blank=True)#审核时的备注
    submitter = models.ForeignKey(User, verbose_name="submitter", \
            related_name="my_cclocks")#请求提交人
    submit_time = models.DateTimeField(auto_now_add = True)#请求提交时间
    approve_time = models.DateTimeField(null=True, blank=True)#审批时间
    attachments = models.TextField(blank=True)#附件，附件格式 "文件名|原始文件名"
    
    #TODO 增加check code
    approve_check_code = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

try:
    admin.site.register(MR)
    admin.site.register(CCLockFlow)
except:
    pass

lock/models.py
from django.db import models

# Create your models here.

flow/cclock/checkmr/forms.py
# -*- coding: UTF-8 -*-
#from django import newforms as forms
from django import forms

STATES_CHOICES = (\
        ('', 'ALL'),\
        ('ReadyForBuild', 'ReadyForBuild'),\
        ('Resolved', 'Resolved'),\
        )

class SearchMRForm(forms.Form):
    """
    查询MR
    """
    start_date = forms.DateField(widget=forms.widgets.TextInput(attrs={'class':'vDateField'}))
    end_date = forms.DateField(widget=forms.widgets.TextInput(attrs={'class':'vDateField'}))
    state = forms.CharField(max_length=3,
                widget=forms.Select(choices=STATES_CHOICES))    

class UpdateMRForm(forms.Form):
    """
    更新MR
    """
    cq_username = forms.CharField(max_length=40,\
            #widget=forms.widgets.TextInput(attrs={'style':'width: 20em;'}),\
            label='Clear Quest用户名', required=False)
    cq_pswd = forms.CharField(max_length=40,\
            widget=forms.widgets.PasswordInput(),\
            label='Clear Quest密码', required=False)

flow/cclock/lock/forms.py
# -*- coding: UTF-8 -*-
from django import forms
from workflow.settings import branch_choices
from workflow.VobConfig.views import get_branch_choices

ACTION_CHOICES=(('q',u'查询'),('assign',u'赋值'),('recover',u'减权'),)

class CCLockForm(forms.Form):
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={'style':'width: 7em;'}), label=u'登录名')
    action = forms.CharField(max_length=3,
                widget=forms.Select(choices=ACTION_CHOICES))
    branch = forms.CharField(max_length=3,
                widget=forms.Select(choices=get_branch_choices()))

    def __init__(self,*args,**kwargs):
        super(CCLockForm,self).__init__(*args,**kwargs)
        self.fields['branch'].widget.choices = get_branch_choices()

flow/cclock/checkmr/views.py
# Create your views here.
# coding: utf-8
from django.shortcuts import render_to_response
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from workflow.flow.cclock.checkmr.forms import SearchMRForm, UpdateMRForm
from workflow.settings import get_mssql_conn
from workflow import settings
from django.http import HttpResponseRedirect

def _str2datetime(value, default_value):
    import datetime
    import time
    format='%Y-%m-%d %H:%M:%S'
    #value='2005-10-20 23:59:59'
    try:
        return datetime.datetime(*time.strptime(value, format)[:6])
    except:
        return default_value

def _format_start_end_date(start, end):
    """
    格式化开始/结束时间
    """
    from datetime import datetime
    start_date=datetime(1990,1,1)
    end_date=datetime(2099,1,1)
    if start:
        start_date = _str2datetime(start + ' 00:01:01', start_date)
    if end:
        end_date = _str2datetime(end + ' 23:59:59', end_date)
    return start_date, end_date

def _get_flow_descn(mr_id):
    """查询出修改了MR的flow"""
    from django.db import connection
    sql = """SELECT title, u.username, approve_time
FROM cclock_cclockflow flow, cclock_cclockflow_bugs f_m, auth_user u
WHERE flow.id = f_m.cclockflow_id
AND f_m.mr_id = %s
AND u.id = flow.submitter_id"""
    cursor = connection.cursor()#dict?
    cursor.execute(sql, (mr_id,))
    t_flows = cursor.fetchall()
    flow_descn = "<br/>".join(["%s/%s/%s" % (e[0],e[1],e[2],) for e in t_flows])
    return flow_descn

#TODO 缺少一个状态类型
_query_mr_sql ="""select distinct(mr.mr_id) from 
cclock_mr mr, cclock_cclockflow flow, cclock_cclockflow_bugs f_m where 
    mr.mr_id=f_m.mr_id 
    and flow.id=f_m.cclockflow_id 
    and flow.approve_result='o'
    and flow.approve_time>=%s
    and flow.approve_time<=%s"""
   
def _get_mr_infos(t_mrs, state):
    """
    重MSSQL中查询出MR信息
    """
    #'ONS00000058','ONS00000059'
    sql = "select id, headline, state_name from dbo.Dev_Projects_MR_Info where id in (%s) "
    mr_ids = ",".join(["'%s'" % e[0] for e in t_mrs])
    if not mr_ids:#如果不包含任何记录直接返回空
        return []
    sql = sql % mr_ids
    if state:
        sql = sql + " and state_name='%s'" % state
    ms_conn=get_mssql_conn()
    ms_cur = ms_conn.cursor()
    ms_cur.execute(sql)
    mrs=ms_cur.fetchall()
    ms_conn.close()
    return mrs

def index(request):
    """
    列出在指定时间段内修改的MR
    MR_ID 申请信息（title/submitter/date）
    """
    form = SearchMRForm(request.GET)
    uform = UpdateMRForm()
    if request.POST:
        """
        如果提交post请求，修改请求的状态
        调用perl脚本，批量修改状态
        """
        uform = UpdateMRForm(request.POST)#由于存在重定向，无法保存CQ表单信息
        import subprocess
        cmd = settings.Update_MR_CMD % (request.POST['cq_username'], \
                request.POST['cq_pswd'], 'ONS', " ".join(request.POST.getlist('selected_mr')))
        p=subprocess.Popen(cmd, cwd=settings.PERL_SCRIPT_DIR, stdout=subprocess.PIPE)    
        p.wait()
        ret = p.communicate()[0].strip()
        if "== create session fail ==" == ret:
            #return HttpResponse("用户名或密码不正确，无法连接Clear Quest");
            request.user.message_set.create(message=u"用户名或密码不正确，无法连接Clear Quest")
        else:
            request.user.message_set.create(message=u"更新成功")
        return HttpResponseRedirect('')#直接返回当前url
    from django.db import connection
    cursor = connection.cursor()#dict?
    from datetime import datetime
    params = _format_start_end_date(request.GET.get('start_date', ''), \
            request.GET.get('end_date', ''))
    cursor.execute(_query_mr_sql, params)
    t_mrs = cursor.fetchall()
    t_mrs = _get_mr_infos(t_mrs, request.GET.get('state', ''))
    mrs = []
    for t_mr in t_mrs:
        mr = {'id': t_mr[0], 'headline': t_mr[1].decode("GBK"), 'state': t_mr[2]}#TODO 当前状态，只显示状态不对的MR？
        mr['flow'] = _get_flow_descn(t_mr[0])
        mrs.append(mr)
    return render_to_response('cclock/checkmr/index.html', \
            {'title': u'ClearCase Lock 改动电子流', 'form':form, 'uform':uform, 'mrs':mrs}, \
        context_instance=template.RequestContext(request))

flow/cclock/lock/views.py
# Create your views here.
# coding: utf-8
from django.shortcuts import render_to_response
from django import template
from workflow.flow.cclock.lock.forms import CCLockForm
from workflow.flow.cclock.lock import clearlock
import approve_log
from workflow.settings import approve_servers, logging
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

def exec_lslock(vobbranch) :
    last_lock = clearlock.ls_lock(vobbranch)
    returnStr = '<strong>Branch & VOB : </strong>' + "<font color='#002BB8'>" + vobbranch + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Remote server : </strong>' + "<font color='#002BB8'>" + approve_servers[vobbranch] + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Lock history : </strong>' + "<font color='#002BB8'>" + last_lock[0] + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Users : </strong>' + "<font color='#002BB8'>" + last_lock[1] + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Return code : </strong>' + "<font color='#002BB8'>" + last_lock[2] + "</font>"
    return returnStr

def exec_assign(eid,vobbranch) :
    logging.debug("[exec_assign | eid, vobbranch]" + eid + ' | ' + vobbranch)
    eid = eid.lower()
    users = ''
    try:
        users = clearlock.getLockExceptUsers(vobbranch)
        if eid.find('hz') != 0 and eid.find('tp') != 0:
            lock_str = 'User id ' + eid +' is invalid'
            ret_code = '1'
        elif (users.find(eid) < 0) :
            users = users + ',' + eid;
            (lock_str,ret_code) = clearlock.replace_lock(vobbranch,users)
        elif (users=='') :
            lock_str = 'Sorry, We Encounter some critical errors!';
            ret_code = '1'
        else :
            lock_str = 'User ' + eid +' already in except list'
            ret_code = '0'#认为是成功的
        if ret_code == '0':#succ
            users = clearlock.getLockExceptUsers(vobbranch)
            if not users.count(eid):
                ret_code = '1'
                lock_str = 'User Limit Apply No Add To Vobbranch'
    except:
        users = 'users' + users + 'xx'
        ret_code = '1'
        lock_str = 'failed, please reference [http://172.18.10.171/rdwiki/images/b/bd/ClearCaseAddLimitProblem.doc]'
    returnStr = '<strong>Branch & VOB : </strong>' + "<font color='#002BB8'>" + vobbranch + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Remote server : </strong>' + "<font color='#002BB8'>" + approve_servers[vobbranch] + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Assign result : </strong>' + "<font color='#002BB8'>" + lock_str + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Current except users : </strong>' + "<font color='#002BB8'>" + users + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Return code : </strong>' + "<font color='#002BB8'>" + ret_code + "</font>" + '<br/>'
    if ret_code=='0' :
        approve_log.logAssign(eid,vobbranch)
    return ret_code, returnStr

def exec_recover(eid,vobbranch) :
    logging.debug("== exec_recover ==")
    eid = eid.lower()
    try:
        users = clearlock.getLockExceptUsers(vobbranch)
        if eid.find('hz') != 0 and eid.find('tp') != 0:
            lock_str = 'User id ' + eid +' is invalid'
            ret_code = '1'
        elif (users.find(eid) > -1) :
            """
            user = ',' + eid
            users = users.replace(user,'')
            """
            logging.debug('[EID, users] #2 ' + eid + ' | ' + users)
            users = users.replace(eid,'')
            users = users.replace(',,', ',')
            users = users.strip(',')
            (lock_str,ret_code) = clearlock.replace_lock(vobbranch,users)
            approve_log.logRecover(eid,vobbranch,False)
            logging.debug('[users, VOBBranch, lock_str, ret_code]' + \
                    users + ' | ' + vobbranch + ' | ' + lock_str + ' | ' + ret_code)
        elif (users=='') :
            lock_str = 'Sorry, We Encounter some critical errors!';
            ret_code = '1'
        else :
            lock_str = 'User ' + eid +' not in except list';
            ret_code = '1'
    except:
        users = ''
        ret_code = '1'
        lock_str = 'failed, unknow error'
    returnStr = '<strong>Branch & VOB : </strong>' + "<font color='#002BB8'>" + vobbranch + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Remote server : </strong>' + "<font color='#002BB8'>" + approve_servers[vobbranch] + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Recover result : </strong>' + "<font color='#002BB8'>" + lock_str + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Current except users : </strong>' + "<font color='#002BB8'>" + users + "</font>" + '<br/>'
    returnStr = returnStr + '<strong>Return code : </strong>' + "<font color='#002BB8'>" + ret_code + "</font>" + '<br/>'
    return ret_code, returnStr

@login_required
def index(request):
    from workflow.settings import admin_user
    if request.user.username not in admin_user:
        return HttpResponse("您没有该权限")
    form = CCLockForm()
    ret = ""
    if request.POST:
        data = request.POST.copy()
        form = CCLockForm(data)
        vobbranch = data['branch']
        eid = data['username']
        action = data['action']
        if 'q' == action:
            ret = exec_lslock(vobbranch)
        if 'assign' == action:
            ret_code, ret = exec_assign(eid,vobbranch)
        if 'recover' == action:
            ret_code, ret = exec_recover(eid,vobbranch)
    return render_to_response('cclock/lock/index.html', \
            {'title': u'ClearCase Lock 改动电子流', 'form': form, 'ret': ret}, \
        context_instance=template.RequestContext(request))

lock/views.py
# Create your views here.

flow/cclock/lock/templates/cclock/lock/cclocks_edit.html
{% extends "base_site.html" %}
{% load i18n %}
{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/forms.css{% endblock %}
{% block extrahead %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/core.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/SelectBox.js"></script>
<script type="text/javascript" src="{% admin_media_prefix %}js/SelectFilter2.js"></script>
{% endblock %}
{% block coltype %}colM{% endblock %}
{% block bodyclass %}auth-group change-form{% endblock %}
{% if not is_popup %}{% block breadcrumbs %}<div class="breadcrumbs"><a href="../../../">{% trans "Home" %}</a> &rsaquo; <a href="../"> ClearCase Lock 改动电子流 </a>&rsaquo; 
{% if add %}{% trans "Add" %} ClearCase Lock 改动电子流 {% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>{% endblock %}{% endif %}
{% block content %}
<div id="content-main">

{% load cclock_filters %}
{% load cclock_tags %}

<script>
    approvers={% approvers %};
    approver_name={% approver_name %};
    function get_vb_approver(vb) {
        if (!vb) return "";
        xs=approvers[vb];
        help_txt="";
        for (i=0;i<xs.length;i++) {
            x=approver_name[xs[i]];
            help_txt+=x+', ';
        }
        return help_txt;
    }
    //选择branch时，显示审批人
    function show_approver(v_b, node) {
        var v_b=document.getElementById(v_b);
        var node=document.getElementById(node);
        v=v_b.value;
        //如果不为空
        node.innerHTML=get_vb_approver(v);
    }
</script>
<form action="" method="post" id="prjreport_form" enctype="multipart/form-data">
<div>
<fieldset class="module aligned ()">
<div class="form-row" >
  <label for="id_title" class="required">标题：</label> 
  {{form.title}}
  {{form.errors.title}}
</div>
<div class="form-row" >
  <label>描述：</label> 
  {{form.descn}}
  {{form.errors.descn}}
</div>
</fieldset>

<fieldset class="module aligned ()">
<div class="form-row" >
  <label class="required"> MR列表：</label> 
  <textarea rows="10" cols="40" name="bugs">{{bugs}}</textarea>
  <p class="help">一行一个MR</p>
  {{form.errors.ext_bugs|safe}}
</div>
<div class="form-row" >
    <label class="required"> Vob branch 1：</label> 
  {{form.vob_branch_1}}
  <p class="help">审批人：<span id="h_b_1"></span></p>
  {{form.errors.vob_branch_1}}
</div>
<div class="form-row" >
  <label> Vob branch 2：</label> 
  {{form.vob_branch_2}}
  <p class="help">审批人：<span id="h_b_2"></span></p>
  {{form.errors.vob_branch_2}}
</div>
<div class="form-row" >
  <label> Vob branch 3：</label> 
  {{form.vob_branch_3}}
  <p class="help">审批人：<span id="h_b_3"></span></p>
  {{form.errors.vob_branch_3}}
</div>
<div class="form-row" >
  <label> Vob branch 4：</label> 
  {{form.vob_branch_4}}
  <p class="help">审批人：<span id="h_b_4"></span></p>
  {{form.errors.vob_branch_4}}
</div>
</fieldset>

<fieldset class="module aligned ()">
<div class="form-row" >
  <label for="id_title" >附件1：</label> 
  <input type="file" name="attachment" size="60"></input>
</div>
<div class="form-row" >
  <label>附件2：</label> 
  <input type="file" name="attachment" size="60"></input>
</div>
<div class="form-row" >
  <label>附件3：</label> 
  <input type="file" name="attachment" size="60"></input>
</div>
</fieldset>

<div class="submit-row">
{%if original%}
<p class="float-left">
<a class="deletelink" href="delete/" onclick="
if (confirm('确认删除？'))
return ture;
else
return false;    
    ">删除</a>
</p>
{%endif%}
<input type="submit" value="保存" class="default" />
</div>
   <script type="text/javascript">document.getElementById("id_title").focus();</script>
</div>
</form>

</div>
<script>
    show_approver("id_vob_branch_1", "h_b_1");
    show_approver("id_vob_branch_2", "h_b_2");
    show_approver("id_vob_branch_3", "h_b_3");
    show_approver("id_vob_branch_4", "h_b_4");
    id_vob_branch_1=document.getElementById("id_vob_branch_1");
    id_vob_branch_1.onchange = function(){show_approver("id_vob_branch_1", "h_b_1");};
    id_vob_branch_2=document.getElementById("id_vob_branch_2");
    id_vob_branch_2.onchange = function(){show_approver("id_vob_branch_2", "h_b_2");};
    id_vob_branch_3=document.getElementById("id_vob_branch_3");
    id_vob_branch_3.onchange = function(){show_approver("id_vob_branch_3", "h_b_3");};
    id_vob_branch_4=document.getElementById("id_vob_branch_4");
    id_vob_branch_4.onchange = function(){show_approver("id_vob_branch_4", "h_b_4");};
</script>
{% endblock %}

flow/cclock/lock/templates/cclock/lock/index.html
{% extends "base_site.html" %}
{% load i18n %}
{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/changelists.css{% endblock %}
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list{% endblock %}
{% if not is_popup %}{% block breadcrumbs %}<div class="breadcrumbs"><a href="../../">{% trans "Home" %}</a> &rsaquo; ClearCase Lock 改动电子流</div>{% endblock %}{% endif %}
{% block content %}
<div id="content-main">

<ul class="object-tools"><li><a href="add/" class="addlink">增加 ClearCase Lock 改动电子流</a></li></ul>

{% load cclock_filters %}
{% load cclock_tags%}
<div class="module filtered" id="changelist">
    <div id="toolbar">
<form action="" method="post">
        &nbsp;
        工号：&nbsp;{{form.username}}
        操作：&nbsp;{{form.action}}
        分支：&nbsp;{{form.branch}}
        <input type="submit" value="提交"/>
    </div>
</form>

<div id="changelist-filter">
<h2>说明</h2>
<h3> 说明 </h3>
<ul>
    <li>暂时没有说明</li>
</ul>
</div>

<div style="padding:10px;">
    {{ret|safe}}
</div>

<p class="paginator">
&nbsp;
</p>

</div>
    
</div>
{% endblock %}