portal/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    # Example:
    # (r'^unicenter/', include('unicenter.foo.urls')),

    # Uncomment this for admin:
    (r'^$', 'workflow.portal.views.index'),
    (r'^login/$', 'workflow.portal.views.login'),
    (r'^t_list/$', 'workflow.portal.views.t_list'),    
    (r'^t_edit/$', 'workflow.portal.views.t_edit'),    
    ('^logout/$', 'django.contrib.auth.views.logout'),    
    ('^password_change/$', 'django.contrib.auth.views.password_change'),        
)

urls.py
from django.conf.urls.defaults import *
from workflow import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
try:
    admin.autodiscover()
except:
    pass

urlpatterns = patterns('',
    # Example:
    # (r'^cclock/', include('cclock.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve',
    #    {'document_root': settings.MEDIA_ROOT}),    
    (r'^admin/(.*)', admin.site.root),
    (r'^mr_flow/',include('workflow.mr_flow.urls')),
    (r'^cclock/', include('workflow.flow.cclock.urls')),
    (r'^mr_review/', include('workflow.MrReview.urls')),
    (r'^spec/', include('workflow.Spec.urls')),
    (r'^', include('workflow.portal.urls')),
    (r'^newfile/', include('workflow.addnewfile.urls')),
    (r'^vob_config/',include('workflow.VobConfig.urls')),
)

workflow/urls.py
from django.conf.urls.defaults import *
from workflow import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
try:
    admin.autodiscover()
except:
    pass

urlpatterns = patterns('',
    # Example:
    # (r'^cclock/', include('cclock.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),    
    (r'^admin/(.*)', admin.site.root),
    (r'^mr_flow/',include('workflow.mr_flow.urls')),
    (r'^cclock/', include('workflow.flow.cclock.urls')),
    (r'^mr_review/', include('workflow.MrReview.urls')),
    (r'^spec/', include('workflow.Spec.urls')),
    (r'^', include('workflow.portal.urls')),
    (r'^newfile/', include('workflow.addnewfile.urls')),
    (r'^vob_config/',include('workflow.VobConfig.urls')),
    (r'^release_tool/',include('workflow.ReleaseTool.urls')),
    (r'^product_manage/',include('workflow.Product.urls')),
)

portal/models.py
# -*- coding: UTF-8 -*-

portal/forms.py
# -*- coding: UTF-8 -*-
from django import newforms as forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=40, widget=forms.widgets.TextInput(\
        attrs={'style':'width: 10em;'}), label=u'登录名')
    password = forms.CharField(max_length=40, widget=forms.widgets.PasswordInput(\
        attrs={'style':'width: 10em;'}), label=u'密码')
    useremail = forms.CharField(max_length=40, widget=forms.widgets.TextInput(\
        attrs={'style':'width: 10em;'}), label=u'邮件')

portal/views.py
# -*- coding: UTF-8 -*-
from django.contrib.auth import SESSION_KEY, REDIRECT_FIELD_NAME
from django.shortcuts import render_to_response
from django import template
from django.template.context import RequestContext
from django.views.generic.list_detail import object_list
from workflow.portal.forms import LoginForm
from django.http import HttpResponseRedirect
from workflow.settings import SITE_NAME
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from get_user_info import get_user_info



@login_required
def index(request):
    return render_to_response('index.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))

def t_list(request):
    from workflow.settings import get_mssql_conn, approvers, CCLOCK_URL, APPROVE_CCLOCK_URL
    from django.http import HttpResponse
    ms_conn=get_mssql_conn()
    ms_cur = ms_conn.cursor()
    query="SELECT id, headline FROM dbo.Dev_Projects_MR_Info where id='%s'" % "ONS00000059"
    ms_cur.execute(query)
    bug=ms_cur.fetchone()
    ms_conn.close()
    #return render_to_response('t_list.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))
    return HttpResponse(bug[1].decode("GBK"))

def t_edit(request):
    return render_to_response('t_edit.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))

def _add_user(username, password):
    user_info = None
    user_info = get_user_info(username)
    if user_info is None:
        user_obj = User.objects.create_user(\
            username=username, email='',\
            password=password)
    else:
        user_obj = User.objects.create_user(\
            username=username, email='',\
            password=password)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
    
    user_obj.is_staff = True
    user_obj.is_superuser = False
    user_obj.save()
    from django.contrib.auth import authenticate
    return authenticate(username=username,\
                        password=password) 

    
def _has_user(username):
    user = None
    try:
        user = User.objects.get(username=username)
    except:
        pass
    return user
    
def  _update_user(username):
    if _has_user(username)  is None:
       return False 
    user_info = None
    user_info = get_user_info(username)
    if user_info is None:
        return True
    else:
        user_obj = User.objects.get(username = username)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
        return True

#检查和校验用户信息是否存在
def _check_and_update_user_info(username):
    user_obj = _has_user(username)
    #用户不存在
    if user_obj is None:
        return False
    if (len(user_obj.email) == 0):
        user_info = None
        user_info = get_user_info(username)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
        user_obj.save()
    return True


unicenter_api_path = r'e:/web/xampp/django_project/unicenter'
def uncenter_auth(username, password):
    import subprocess
    cmd = 'python uc_api.py' + ' auth "%s" "%s" utscn' % (username, password)
    p=subprocess.Popen(['D:/Python25/python.exe', 'uc_api.py', 'auth', username, password, 'utscn'], cwd=unicenter_api_path, stdout=subprocess.PIPE)
    # p.wait()
    ret = p.communicate()[0].strip()
    return "True" == ret


# 邮件地址由discuz中获取
def login(request):
    # 进行域认证，如果用户不存在创建用户
    error_message=""
    redirect_to = request.REQUEST.get(REDIRECT_FIELD_NAME, '/')
    form = LoginForm()
    set_email = False
    if request.POST:
        error_message=u"登录失败"
        form = LoginForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            # 做域认证
            username = data['username']
            password = data['password']
            auth_ret = uncenter_auth(username,password)
            user = None
            if auth_ret:
                user = _has_user(username)
                if not user:
                    user = _add_user(username,password)
                if user:
                    user.set_password(password)
                    user.save()
            else:
                pass
            #校验用户信息是否完整，并自动完善
            if username is not 'admin':
                _check_and_update_user_info(username)
            #使本地认证通过
            from django.contrib import auth
            user = auth.authenticate(username=username,\
            password=password)
            if user  is not None:
                auth.login(request, user)
                return HttpResponseRedirect(redirect_to)
            else:
                error_message=u"您输入的用户名或密码不正确，请使用域账户/密码登陆！"
    return render_to_response('login.html', {'error_message': error_message,
                                             'set_email':set_email,
                                             'title': u'统一认证管理中心'}, context_instance=template.RequestContext(request))

workflow/portal/views.py
# -*- coding: UTF-8 -*-
from django.contrib.auth import SESSION_KEY, REDIRECT_FIELD_NAME
from django.shortcuts import render_to_response
from django import template
from django.template.context import RequestContext
from django.views.generic.list_detail import object_list
from workflow.portal.forms import LoginForm
from django.http import HttpResponseRedirect
from workflow.settings import SITE_NAME
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from get_user_info import get_user_info

from workflow.VobConfig.views import update_all_vob_config
from workflow.settings import HOST_NAME

@login_required
def index(request):
    update_all_vob_config()
    return render_to_response('index.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))

def t_list(request):
    from workflow.settings import get_mssql_conn, approvers, CCLOCK_URL, APPROVE_CCLOCK_URL
    from django.http import HttpResponse
    ms_conn=get_mssql_conn()
    ms_cur = ms_conn.cursor()
    query="SELECT id, headline FROM dbo.Dev_Projects_MR_Info where id='%s'" % "ONS00000059"
    ms_cur.execute(query)
    bug=ms_cur.fetchone()
    ms_conn.close()
    #return render_to_response('t_list.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))
    return HttpResponse(bug[1].decode("GBK"))

def t_edit(request):
    return render_to_response('t_edit.html', {'title': SITE_NAME}, context_instance=template.RequestContext(request))

def _add_user(username, password):
    user_info = None
    user_info = get_user_info(username)
    if user_info is None:
        user_obj = User.objects.create_user(\
            username=username, email='',\
            password=password)
    else:
        user_obj = User.objects.create_user(\
            username=username, email='',\
            password=password)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
    
    user_obj.is_staff = True
    user_obj.is_superuser = False
    user_obj.save()
    from django.contrib.auth import authenticate
    return authenticate(username=username,\
                        password=password) 

    
def _has_user(username):
    user = None
    try:
        user = User.objects.get(username=username)
    except:
        pass
    return user
    
def  _update_user(username):
    if _has_user(username)  is None:
       return False 
    user_info = None
    user_info = get_user_info(username)
    if user_info is None:
        return True
    else:
        user_obj = User.objects.get(username = username)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
        return True

#检查和校验用户信息是否存在
def _check_and_update_user_info(username):
    user_obj = _has_user(username)
    #用户不存在
    if user_obj is None:
        return False
    if (len(user_obj.email) == 0):
        user_info = None
        user_info = get_user_info(username)
        user_obj.email = user_info['email']
        user_obj.first_name = user_info['c_name']
        user_obj.last_name = user_info['e_name']
        user_obj.save()
    return True


unicenter_api_path = r'e:/web/xampp/django_project/unicenter'
# 邮件地址由discuz中获取


def login(request):
    # 进行域认证，如果用户不存在创建用户
    error_message=""
    redirect_to = request.REQUEST.get(REDIRECT_FIELD_NAME, '/')
    form = LoginForm()
    set_email = False
    if request.POST:

        data = request.POST.copy()
        # 做域认证
        username = data['username']
        password = data['password']
        username = username.lower()
        #域用户认证, admin用户除外
        #----------------------------------------------------------------
        if HOST_NAME == 'HZ_RD_WUSHUMING' or HOST_NAME == 'HZ_RD_SERVER':
            import ldap
            if username is not 'admin':
                try:
                    conn = ldap.initialize('ldap://172.18.9.21')
                    conn.simple_bind_s('utscn\\'+username, password)
                    user = _has_user(username)
                    if not user:#如果用户不存在，创建用户
                        user = _add_user(username, password)
                    if user:#更新用户密码，保证使用django内部认证时可以通过
                        user.set_password(password)
                        user.save()
                except:
                    pass    #auth failed
        #校验用户信息是否完整，并自动完善
        if username is not 'admin':
            _check_and_update_user_info(username)
        #-------------------------------------------------------------------
        from django.contrib import auth
        user = auth.authenticate(username=username,\
        password=password)
        if user  is not None:
            auth.login(request, user)
            redirect_to = '/workflow/vob_config/all/'
            return HttpResponseRedirect(redirect_to)
        else:
            error_message=u"您输入的用户名或密码不正确，请使用域账户/密码登陆！"
    return render_to_response('login.html', {'error_message': error_message,
                                             'set_email':set_email,
                                             'title': u'统一认证管理中心'}, context_instance=template.RequestContext(request))

portal/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% load adminmedia %}{% admin_media_prefix %}css/base.css" />
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/base.css{% endblock %}" />
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% admin_media_prefix %}css/rtl.css{% endblock %}" />{% endif %}
{% block extrastyle %}{% endblock %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_authenticated and user.is_staff %}
        <div id="user-tools">
        {% trans 'Welcome,' %} <strong>{% if user.first_name %}{{ user.first_name|escape }}{% else %}{{ user.username }}{% endif %}</strong>.
        {% block userlinks %}
        <a href="">{% trans 'Documentation' %}</a>
        {% load websetting %}
        / <a href="/{% url_prefix %}/password_change/">{% trans 'Change password' %}</a>
        / <a href="/{% url_prefix %}/logout/">{% trans 'Log out' %}</a>
        {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}<div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a>{% if title %} &rsaquo; {{ title|escape }}{% endif %}</div>{% endblock %}
    {% endif %}

        {% if messages %}
        <ul class="messagelist">{% for message in messages %}<li>{{ message|safe }}</li>{% endfor %}</ul>
        {% endif %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title|escape }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

portal/templates/base_site.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Django site admin' %}{% endblock %}

{% block branding %}
{% load websetting %}
<h1 id="site-name">{% site_name %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

portal/templates/index.html
{% extends "base_site.html" %}
{% load i18n %}

{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/dashboard.css{% endblock %}
{% block coltype %}colMS{% endblock %}
{% block bodyclass %}dashboard{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block content %}
<div id="content-main">

	<div class="module">
	<table>
	<caption>ClearCase Lock 改动电子流</caption>
		<tr>
			<th scope="row"><a href="cclock/my/?q_approve_result=u">我提交的请求</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="cclock/todo/q_approve_result=o">查看所有通过审核的请求</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="cclock/todo/query">根据规则过滤审核请求</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="cclock/todo/?q_approve_result=u">待审核的请求</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="vob_config/all/">分支信息管理</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="cclock/lock/">ClearCase权限管理</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
	<table>
	<caption>ClearQuest MR 改动电子流</caption>
		<tr>
			<th scope="row"><a href="cclock/checkmr/?state=ReadyForBuild">批量更新MR状态（Resolved）</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="mr_flow/edit">新建一个MR</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
	<table>
	<caption>Review 信息电子流</caption>
		<tr>
			<th scope="row"><a href="mr_review/todo/query">根据规则过滤review信息</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
	<table>
	<caption>规格电子流</caption>
		<tr>
			<th scope="row"><a href="spec/add">规格ID申请</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="spec/todo/query">规格ID查询</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
	<table>
	<caption>ClearCase新建空文件</caption>
		<tr>
			<th scope="row"><a href="newfile/add">ClearCase上新建空文件</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<th scope="row"><a href="newfile/query">查询在ClearCase上新建的文件</a></th>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</table>
	</div>
	
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>公告</h2>
        <h3>使用说明</h3>
		<p>最新的使用说明请参考wiki<a href="http://172.18.10.171/wiki/BetterFlow/workflow"><br/>《使用说明》</a></p>
    </div>
</div>
{% endblock %}

portal/templates/login.html
{% extends "base_site.html" %}
{% load i18n %}

{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/login.css{% endblock %}
{% block bodyclass %}login{% endblock %}
{% block content_title %}{% endblock %}
{% block breadcrumbs %}{% endblock %}

{% block content %}

{% if error_message %}
<p class="errornote">{{ error_message }}</p>
{% endif %}
<div id="content-main">
<form action="{{ app_path }}" method="post" id="login-form">
  <div class="form-row">
    <label for="id_username">{% trans 'Username:' %}</label> <input type="text" name="username" id="id_username" />
  </div>
  <div class="form-row">
	  <label for="id_password">{% trans 'Password:' %}</label> <input type="password" name="password" id="id_password" />
	  <input type="hidden" name="this_is_the_login_form" value="1" />
	  <input type="hidden" name="post_data" value="{{ post_data }}" /> {#<span class="help">{% trans 'Have you <a href="/password_reset/">forgotten your password</a>?' %}</span>#}
  </div>
  <div class="form-row">
  {% if set_email %}
	  <label for="id_useremail">{% trans 'Useremail:' %}</label> <input type="text" name="useremail" id="id_useremail" />
	  <script>
		  document.getElementById('id_useremail').value='please set email';
	  </script>
  {% else %}
	  <input type="hidden" name="useremail" id="id_useremail" />
	  <script>
		  document.getElementById('id_useremail').value='---------';
	  </script>
  {% endif %}
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

portal/templates/t_edit.html
{% extends "base_site.html" %}
{% load i18n %}
{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/forms.css{% endblock %}
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list{% endblock %}
{% if not is_popup %}{% block breadcrumbs %}<div class="breadcrumbs"><a href="../../">{% trans "Home" %}</a> &rsaquo; 用户</div>{% endblock %}{% endif %}
{% block content %}
<div id="content-main">

<form action="" method="post" id="site_form">
<div>



   <fieldset class="module aligned ()">
    
    
    
        
<div class="form-row" >


  <label for="id_domain" class="required">域名:</label> 
  <input type="text" id="id_domain" class="vTextField required" name="domain" size="30" value="" maxlength="100" />

  
  

</div>

        
            
        
    
        
<div class="form-row" >


  <label for="id_name" class="required">显示名称:</label> 
  <input type="text" id="id_name" class="vTextField required" name="name" size="30" value="" maxlength="50" />

  
  

</div>

        
            
        
    
   </fieldset>





<div class="submit-row">


<input type="submit" value="保存并增加另一个" name="_addanother"  />
<input type="submit" value="保存并继续编辑" name="_continue" />
<input type="submit" value="保存" class="default" />
</div>


   <script type="text/javascript">document.getElementById("id_domain").focus();</script>


</div>
</form>	
    
</div>
{% endblock %}

portal/templates/t_list.html
{% extends "base_site.html" %}
{% load i18n %}
{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/changelists.css{% endblock %}
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list{% endblock %}
{% if not is_popup %}{% block breadcrumbs %}<div class="breadcrumbs"><a href="../../">{% trans "Home" %}</a> &rsaquo; 用户</div>{% endblock %}{% endif %}
{% block content %}
<div id="content-main">

<ul class="object-tools"><li><a href="add/" class="addlink">增加 用户</a></li></ul>

<div class="module filtered" id="changelist">


<div id="toolbar"><form id="changelist-search" action="" method="get">
<div><!-- DIV needed for valid HTML -->
<label for="searchbar"><img src="{% admin_media_prefix %}img/admin/icon_searchbox.png" alt="Search" /></label>
<input type="text" size="40" name="q" value="" id="searchbar" />
<input type="submit" value="执行" />


</div>
</form></div>
<script type="text/javascript">document.getElementById("searchbar").focus();</script>





<div id="changelist-filter">
<h2>过滤器</h2>

   
<h3> 以 职员状态</h3>
<ul>

    <li class="selected">
    <a href="?">全部</a></li>

    <li>
    <a href="?is_staff__exact=1">是</a></li>

    <li>
    <a href="?is_staff__exact=0">否</a></li>

</ul>


   

<h3> 以 超级用户状态</h3>
<ul>

    <li class="selected">
    <a href="?">全部</a></li>

    <li>
    <a href="?is_superuser__exact=1">是</a></li>

    <li>
    <a href="?is_superuser__exact=0">否</a></li>

</ul>

</div>


<table cellspacing="0">
<thead>
<tr>
<th class="sorted ascending">
<a href="?ot=desc&amp;o=0">
用户名

</a></th><th>
<a href="?ot=asc&amp;o=1">
E-mail 地址
</a></th><th>
<a href="?ot=asc&amp;o=2">
名字
</a></th><th>
<a href="?ot=asc&amp;o=3">
姓氏
</a></th><th>
<a href="?ot=asc&amp;o=4">
职员状态
</a></th>
</tr>
</thead>
<tbody>

<tr class="row1"><th><a href="1/">admin</a></th><td>vik@vicalloy.org</td><td>&nbsp;</td><td>&nbsp;</td><td><img src="/media/img/admin/icon-yes.gif" alt="1" /></td></tr>

</tbody>
</table>




<p class="paginator">

1 用户

</p>

</div>
    
</div>
{% endblock %}

portal/templates/user_list.html
{% extends "base_site.html" %}
{% load i18n %}
{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/changelists.css{% endblock %}
{% block coltype %}flex{% endblock %}
{% block bodyclass %}change-list{% endblock %}
{% if not is_popup %}{% block breadcrumbs %}<div class="breadcrumbs"><a href="/">{% trans "Home" %}</a> &rsaquo; 用户</div>{% endblock %}{% endif %}
{% block content %}
<div id="content-main">

<ul class="object-tools"><li><a href="add/" class="addlink">增加 用户</a></li></ul>

<div class="module filtered" id="changelist">


<div id="toolbar"><form id="changelist-search" action="" method="get">
<div><!-- DIV needed for valid HTML -->
<label for="searchbar"><img src="/media/img/admin/icon_searchbox.png" alt="Search" /></label>
<input type="text" size="40" name="q" value="{{q}}" id="searchbar" />
<input type="submit" value="执行" />


</div>
</form></div>
<script type="text/javascript">document.getElementById("searchbar").focus();</script>





<div id="changelist-filter">
<h2>过滤器</h2>
   
<h3> 组 </h3>
<ul>
    {{group_filtre|safe}}
</ul>


</div>


<table cellspacing="0">
	<thead>
		<tr>
			<th>用户名</th>
            <th>E-Mail</th>
			<th>组</th>
		</tr>
	</thead>
	<tbody>
		{% for o in users%}
		<tr class="row1">
			<th><a href="{{o.uid}}/">{{o.username}}</a></th>
            <td>{{o.email}}</td>
			<td>{{o.html_groups|safe}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>




<p class="paginator">



</p>

</div>
    
</div>
{% endblock %}